### ISSUE TITLE
Debugging action issues; deploying a forked action

### ISSUE THREAD

**Issue by k-stachowiak** [alex-page/github-project-automation-plus#15]
First of all, thanks for publishing the action. It looks very promising.
As a non-javascript programmer I experienced some issues debugging the solution and tried to use my own fork of this repository to add some extra logging information.
It wasn't easy for me to establish, what exactly needs to be done to have the `dist` directory contain a valid script. Eventually I've got it to work by a combination of `npm run-script build`, `npm build .` and maybe `npm audit`.

I'm still not sure, what I did to get it to work, which is obviously due to my npm ignorance. Nevertheless, I think it would be very helpful and not at all troublesome to include a paragraph in the readme file, that explains, how to build the action.

Note: this entry contained a lengthy description of my struggle, before I managed to overcome it.

**Comment by alex-page** [comment]
Hey @k-stachowiak. Here are some instructions for local development:
1. Install dependencies `npm install`
1. Make the changes to the package
1. Build the action `npm run build`. This is required because the `node_modules` that are installed need to be bundled into the `dist` directory when the code is pushed to GitHub. You can read more here: https://help.github.com/en/articles/creating-a-javascript-action#commit-and-push-your-action-to-github
1. Commit and push built files to GitHub `git commit -m "New action" && git push`
1. When you are using your forked version of the action in the workflow `.yml` file make sure your reference it like: `uses: k-stachowiak/github-project-automation-plus@master`

Let me know if you have any problems following these steps. `npm audit` is for fixing security issues with `npm` dependencies. You shouldn't need to run this in your fork to get it to work.

**Comment by k-stachowiak** [comment]
Thanks for your reply. I have managed to get my fork working, and it was very helpful e.g. to print the contents of the payload structure and catch errors in my condition expressions. Nevertheless, thanks for the instructions; it's good to know the right way of doing things.
