### ISSUE TITLE
Automate moving issue to be fixed by a PR?

### ISSUE THREAD

**Issue by hugovk** [alex-page/github-project-automation-plus#9]
Would something like this be possible or in scope for this action?

* When a PR is created, look for "Fixes #XXX" (or "Fixes https://github.com/org/repo/pull/XXX") in the text

* Move issue XXX to the "Pull requested" column of a project

Thanks for this handy project!

**Comment by alex-page** [comment]
Hey @hugovk, this sounds like a great idea. As of right now I am trying to keep the scope of this project to webhooks. This would definitely be achievable however it would probably be a fork of this project as it would need to trigger the action when the issue is linked to the pull request.

As of right now there isn't a [webhook](https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events) to do this:

> Triggered when an issue is opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, or demilestoned.

**Comment by hugovk** [comment]
OK, thanks!
